/**
 * TypeScript types for Comment
 * Auto-generated by schema-registry module
 *
 * Re-exported from Zod schemas — do not define types manually here.
 */

export type { Comment, CommentCreate, CommentUpdate } from "@/lib/schemas/comment";
