/**
 * TypeScript types for Invoice
 * Auto-generated by schema-registry module
 *
 * Re-exported from Zod schemas — do not define types manually here.
 */

export type { Invoice, InvoiceCreate, InvoiceUpdate } from "@/lib/schemas/invoice";
