/**
 * TypeScript types for MediaFile
 * Auto-generated by schema-registry module
 *
 * Re-exported from Zod schemas — do not define types manually here.
 */

export type { MediaFile, MediaFileCreate, MediaFileUpdate } from "@/lib/schemas/media-file";
