/**
 * TypeScript types for PricingPlan
 * Auto-generated by schema-registry module
 *
 * Re-exported from Zod schemas — do not define types manually here.
 */

export type { PricingPlan, PricingPlanCreate, PricingPlanUpdate } from "@/lib/schemas/pricing-plan";
