/**
 * TypeScript types for Reaction
 * Auto-generated by schema-registry module
 *
 * Re-exported from Zod schemas — do not define types manually here.
 */

export type { Reaction, ReactionCreate, ReactionUpdate } from "@/lib/schemas/reaction";
