/**
 * Feature Flags
 *
 * Typed feature flag definitions derived from enabled modules.
 * Flags can be overridden per-user or per-tenant via Supabase.
 *
 * @generated by feature-flags module
 */

export interface FeatureFlags {
  /** Module: app-shell */
  appShell: boolean;
  /** Module: auth-email-otp */
  authEmailOtp: boolean;
  /** Module: checkout-flow */
  checkoutFlow: boolean;
  /** Module: comments-threaded */
  commentsThreaded: boolean;
  /** Module: crud-scaffolder */
  crudScaffolder: boolean;
  /** Module: design-system */
  designSystem: boolean;
  /** Module: empty-skeleton-states */
  emptySkeletonStates: boolean;
  /** Module: env-schema */
  envSchema: boolean;
  /** Module: error-boundary */
  errorBoundary: boolean;
  /** Module: feature-flags */
  featureFlags: boolean;
  /** Module: file-storage-adapter */
  fileStorageAdapter: boolean;
  /** Module: filter-engine */
  filterEngine: boolean;
  /** Module: form-engine */
  formEngine: boolean;
  /** Module: fulltext-provider-interface */
  fulltextProviderInterface: boolean;
  /** Module: global-search */
  globalSearch: boolean;
  /** Module: icons-assets */
  iconsAssets: boolean;
  /** Module: invoices-receipts */
  invoicesReceipts: boolean;
  /** Module: media-library */
  mediaLibrary: boolean;
  /** Module: media-uploader */
  mediaUploader: boolean;
  /** Module: messaging-inbox */
  messagingInbox: boolean;
  /** Module: messaging-realtime-interface */
  messagingRealtimeInterface: boolean;
  /** Module: nav-composer */
  navComposer: boolean;
  /** Module: notifications-email */
  notificationsEmail: boolean;
  /** Module: notifications-inapp */
  notificationsInapp: boolean;
  /** Module: payments-provider-interface */
  paymentsProviderInterface: boolean;
  /** Module: pricing-plans */
  pricingPlans: boolean;
  /** Module: reactions */
  reactions: boolean;
  /** Module: routing-composer */
  routingComposer: boolean;
  /** Module: schema-registry */
  schemaRegistry: boolean;
  /** Module: seo-meta-manager */
  seoMetaManager: boolean;
  /** Module: session-management */
  sessionManagement: boolean;
  /** Module: settings-registry */
  settingsRegistry: boolean;
  /** Module: static-pages */
  staticPages: boolean;
  /** Module: subscriptions */
  subscriptions: boolean;
  /** Module: table-engine */
  tableEngine: boolean;
  /** Module: theme-engine */
  themeEngine: boolean;
  /** Module: user-profile */
  userProfile: boolean;
  /** Module: user-settings */
  userSettings: boolean;
}

/**
 * Default flag values (all enabled modules start as true).
 */
export const defaultFlags: FeatureFlags = {
  appShell: true,
  authEmailOtp: true,
  checkoutFlow: true,
  commentsThreaded: true,
  crudScaffolder: true,
  designSystem: true,
  emptySkeletonStates: true,
  envSchema: true,
  errorBoundary: true,
  featureFlags: true,
  fileStorageAdapter: true,
  filterEngine: true,
  formEngine: true,
  fulltextProviderInterface: true,
  globalSearch: true,
  iconsAssets: true,
  invoicesReceipts: true,
  mediaLibrary: true,
  mediaUploader: true,
  messagingInbox: true,
  messagingRealtimeInterface: true,
  navComposer: true,
  notificationsEmail: true,
  notificationsInapp: true,
  paymentsProviderInterface: true,
  pricingPlans: true,
  reactions: true,
  routingComposer: true,
  schemaRegistry: true,
  seoMetaManager: true,
  sessionManagement: true,
  settingsRegistry: true,
  staticPages: true,
  subscriptions: true,
  tableEngine: true,
  themeEngine: true,
  userProfile: true,
  userSettings: true,
};

/**
 * All known flag keys for iteration.
 */
export const FLAG_KEYS: ReadonlyArray<keyof FeatureFlags> = [
  "appShell",
  "authEmailOtp",
  "checkoutFlow",
  "commentsThreaded",
  "crudScaffolder",
  "designSystem",
  "emptySkeletonStates",
  "envSchema",
  "errorBoundary",
  "featureFlags",
  "fileStorageAdapter",
  "filterEngine",
  "formEngine",
  "fulltextProviderInterface",
  "globalSearch",
  "iconsAssets",
  "invoicesReceipts",
  "mediaLibrary",
  "mediaUploader",
  "messagingInbox",
  "messagingRealtimeInterface",
  "navComposer",
  "notificationsEmail",
  "notificationsInapp",
  "paymentsProviderInterface",
  "pricingPlans",
  "reactions",
  "routingComposer",
  "schemaRegistry",
  "seoMetaManager",
  "sessionManagement",
  "settingsRegistry",
  "staticPages",
  "subscriptions",
  "tableEngine",
  "themeEngine",
  "userProfile",
  "userSettings"
] as const;

/**
 * Check if a specific feature is enabled.
 */
export function isFeatureEnabled(
  flags: FeatureFlags,
  key: keyof FeatureFlags
): boolean {
  return flags[key] === true;
}

/**
 * Merge partial overrides into default flags.
 * Useful for user-specific or tenant-specific overrides from DB.
 */
export function mergeFlags(overrides: Partial<FeatureFlags>): FeatureFlags {
  return { ...defaultFlags, ...overrides };
}

/**
 * Fetch flag overrides from Supabase for a given user.
 * Returns partial overrides (only changed flags).
 */
export async function fetchUserFlags(
  supabase: { from: (table: string) => { select: (cols: string) => { eq: (col: string, val: string) => { single: () => Promise<{ data: Record<string, unknown> | null }> } } } },
  userId: string
): Promise<Partial<FeatureFlags>> {
  const { data } = await supabase
    .from("user_feature_flags")
    .select("flags")
    .eq("user_id", userId)
    .single();

  if (!data || !data.flags) return {};
  return data.flags as Partial<FeatureFlags>;
}
