/**
 * App Settings
 *
 * Typed settings registry with global config and per-module settings.
 * Defaults are generated from enabled modules. User overrides are
 * loaded from Supabase at runtime.
 *
 * @generated by settings-registry module
 */

// === Global Settings ===

export interface GlobalSettings {
  /** Application display name */
  appName: string;
  /** Default locale */
  locale: string;
  /** Timezone for date formatting */
  timezone: string;
  /** Theme mode */
  themeMode: "dark" | "light" | "system";
  /** Primary brand color */
  primaryColor: string;
  /** Items per page for pagination */
  pageSize: number;
  /** Enable maintenance mode */
  maintenanceMode: boolean;
}

export const defaultGlobalSettings: GlobalSettings = {
  appName: "PantyHub",
  locale: "en",
  timezone: "UTC",
  themeMode: "dark",
  primaryColor: "#660033",
  pageSize: 20,
  maintenanceMode: false,
};

// === Per-Module Settings ===

export interface AppShellSettings {
  enabled: boolean;
}

export interface AuthEmailOtpSettings {
  enabled: boolean;
}

export interface CheckoutFlowSettings {
  enabled: boolean;
}

export interface CommentsThreadedSettings {
  enabled: boolean;
}

export interface CrudScaffolderSettings {
  enabled: boolean;
}

export interface DesignSystemSettings {
  enabled: boolean;
}

export interface EmptySkeletonStatesSettings {
  enabled: boolean;
}

export interface EnvSchemaSettings {
  enabled: boolean;
}

export interface ErrorBoundarySettings {
  enabled: boolean;
}

export interface FeatureFlagsSettings {
  enabled: boolean;
}

export interface FileStorageAdapterSettings {
  enabled: boolean;
}

export interface FilterEngineSettings {
  enabled: boolean;
}

export interface FormEngineSettings {
  enabled: boolean;
}

export interface FulltextProviderInterfaceSettings {
  enabled: boolean;
}

export interface GlobalSearchSettings {
  enabled: boolean;
}

export interface IconsAssetsSettings {
  enabled: boolean;
}

export interface InvoicesReceiptsSettings {
  enabled: boolean;
}

export interface MediaLibrarySettings {
  enabled: boolean;
}

export interface MediaUploaderSettings {
  enabled: boolean;
}

export interface MessagingInboxSettings {
  enabled: boolean;
}

export interface MessagingRealtimeInterfaceSettings {
  enabled: boolean;
}

export interface NavComposerSettings {
  enabled: boolean;
}

export interface NotificationsEmailSettings {
  enabled: boolean;
}

export interface NotificationsInappSettings {
  enabled: boolean;
}

export interface PaymentsProviderInterfaceSettings {
  enabled: boolean;
}

export interface PricingPlansSettings {
  enabled: boolean;
}

export interface ReactionsSettings {
  enabled: boolean;
}

export interface RoutingComposerSettings {
  enabled: boolean;
}

export interface SchemaRegistrySettings {
  enabled: boolean;
}

export interface SeoMetaManagerSettings {
  enabled: boolean;
}

export interface SessionManagementSettings {
  enabled: boolean;
}

export interface SettingsRegistrySettings {
  enabled: boolean;
}

export interface StaticPagesSettings {
  enabled: boolean;
}

export interface SubscriptionsSettings {
  enabled: boolean;
}

export interface TableEngineSettings {
  enabled: boolean;
}

export interface ThemeEngineSettings {
  enabled: boolean;
}

export interface UserProfileSettings {
  enabled: boolean;
}

export interface UserSettingsSettings {
  enabled: boolean;
}

export interface ModuleSettings {
  appShell: AppShellSettings;
  authEmailOtp: AuthEmailOtpSettings;
  checkoutFlow: CheckoutFlowSettings;
  commentsThreaded: CommentsThreadedSettings;
  crudScaffolder: CrudScaffolderSettings;
  designSystem: DesignSystemSettings;
  emptySkeletonStates: EmptySkeletonStatesSettings;
  envSchema: EnvSchemaSettings;
  errorBoundary: ErrorBoundarySettings;
  featureFlags: FeatureFlagsSettings;
  fileStorageAdapter: FileStorageAdapterSettings;
  filterEngine: FilterEngineSettings;
  formEngine: FormEngineSettings;
  fulltextProviderInterface: FulltextProviderInterfaceSettings;
  globalSearch: GlobalSearchSettings;
  iconsAssets: IconsAssetsSettings;
  invoicesReceipts: InvoicesReceiptsSettings;
  mediaLibrary: MediaLibrarySettings;
  mediaUploader: MediaUploaderSettings;
  messagingInbox: MessagingInboxSettings;
  messagingRealtimeInterface: MessagingRealtimeInterfaceSettings;
  navComposer: NavComposerSettings;
  notificationsEmail: NotificationsEmailSettings;
  notificationsInapp: NotificationsInappSettings;
  paymentsProviderInterface: PaymentsProviderInterfaceSettings;
  pricingPlans: PricingPlansSettings;
  reactions: ReactionsSettings;
  routingComposer: RoutingComposerSettings;
  schemaRegistry: SchemaRegistrySettings;
  seoMetaManager: SeoMetaManagerSettings;
  sessionManagement: SessionManagementSettings;
  settingsRegistry: SettingsRegistrySettings;
  staticPages: StaticPagesSettings;
  subscriptions: SubscriptionsSettings;
  tableEngine: TableEngineSettings;
  themeEngine: ThemeEngineSettings;
  userProfile: UserProfileSettings;
  userSettings: UserSettingsSettings;
}

export const defaultModuleSettings: ModuleSettings = {
  appShell: {
    enabled: true,
  },
  authEmailOtp: {
    enabled: true,
  },
  checkoutFlow: {
    enabled: true,
  },
  commentsThreaded: {
    enabled: true,
  },
  crudScaffolder: {
    enabled: true,
  },
  designSystem: {
    enabled: true,
  },
  emptySkeletonStates: {
    enabled: true,
  },
  envSchema: {
    enabled: true,
  },
  errorBoundary: {
    enabled: true,
  },
  featureFlags: {
    enabled: true,
  },
  fileStorageAdapter: {
    enabled: true,
  },
  filterEngine: {
    enabled: true,
  },
  formEngine: {
    enabled: true,
  },
  fulltextProviderInterface: {
    enabled: true,
  },
  globalSearch: {
    enabled: true,
  },
  iconsAssets: {
    enabled: true,
  },
  invoicesReceipts: {
    enabled: true,
  },
  mediaLibrary: {
    enabled: true,
  },
  mediaUploader: {
    enabled: true,
  },
  messagingInbox: {
    enabled: true,
  },
  messagingRealtimeInterface: {
    enabled: true,
  },
  navComposer: {
    enabled: true,
  },
  notificationsEmail: {
    enabled: true,
  },
  notificationsInapp: {
    enabled: true,
  },
  paymentsProviderInterface: {
    enabled: true,
  },
  pricingPlans: {
    enabled: true,
  },
  reactions: {
    enabled: true,
  },
  routingComposer: {
    enabled: true,
  },
  schemaRegistry: {
    enabled: true,
  },
  seoMetaManager: {
    enabled: true,
  },
  sessionManagement: {
    enabled: true,
  },
  settingsRegistry: {
    enabled: true,
  },
  staticPages: {
    enabled: true,
  },
  subscriptions: {
    enabled: true,
  },
  tableEngine: {
    enabled: true,
  },
  themeEngine: {
    enabled: true,
  },
  userProfile: {
    enabled: true,
  },
  userSettings: {
    enabled: true,
  },
};

// === Combined Settings ===

export interface AppSettings {
  global: GlobalSettings;
  modules: ModuleSettings;
}

export const defaultSettings: AppSettings = {
  global: defaultGlobalSettings,
  modules: defaultModuleSettings,
};

/**
 * Deep merge settings overrides into defaults.
 */
export function mergeSettings(overrides: Partial<AppSettings>): AppSettings {
  return {
    global: { ...defaultGlobalSettings, ...overrides.global },
    modules: {
      ...defaultModuleSettings,
      ...Object.fromEntries(
        Object.entries(overrides.modules ?? {}).map(([key, val]) => [
          key,
          { ...(defaultModuleSettings as unknown as Record<string, Record<string, unknown>>)[key], ...val },
        ])
      ),
    } as ModuleSettings,
  };
}
