/**
 * CRUD hooks for Channel
 * Auto-generated by crud-scaffolder module
 *
 * These hooks call API routes (not Supabase directly) since they run client-side.
 */

"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import type { Channel, ChannelCreate, ChannelUpdate } from "@/lib/schemas/channel";

interface Pagination {
  page: number;
  limit: number;
  total: number;
  totalPages: number;
}

interface UseChannelsOptions {
  page?: number;
  limit?: number;
  sort?: string;
  order?: "asc" | "desc";
  search?: string;
  enabled?: boolean;
}

interface UseChannelsResult {
  data: Channel[];
  pagination: Pagination | null;
  isLoading: boolean;
  error: string | null;
  refetch: () => Promise<void>;
  create: (input: ChannelCreate) => Promise<Channel | null>;
  update: (id: string, input: ChannelUpdate) => Promise<Channel | null>;
  remove: (id: string) => Promise<boolean>;
}

export function useChannels(options: UseChannelsOptions = {}): UseChannelsResult {
  const { page = 1, limit = 20, sort = "created_at", order = "desc", search, enabled = true } = options;
  const [data, setData] = useState<Channel[]>([]);
  const [pagination, setPagination] = useState<Pagination | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const abortRef = useRef<AbortController | null>(null);

  const fetchData = useCallback(async () => {
    if (!enabled) return;

    // Cancel any in-flight request
    abortRef.current?.abort();
    const controller = new AbortController();
    abortRef.current = controller;

    setIsLoading(true);
    setError(null);
    try {
      const params = new URLSearchParams({
        page: String(page),
        limit: String(limit),
        sort,
        order,
      });
      if (search) params.set("search", search);

      const res = await fetch(`/api/channels?${params}`, {
        signal: controller.signal,
      });
      if (!res.ok) {
        const body = await res.json();
        throw new Error(body.error?.message || "Failed to fetch channels");
      }
      const json = await res.json();
      setData(json.data);
      setPagination(json.pagination);
    } catch (e) {
      if (e instanceof DOMException && e.name === "AbortError") return;
      setError(e instanceof Error ? e.message : "Unknown error");
    } finally {
      setIsLoading(false);
    }
  }, [page, limit, sort, order, search, enabled]);

  useEffect(() => {
    fetchData();
    return () => { abortRef.current?.abort(); };
  }, [fetchData]);

  const create = useCallback(async (input: ChannelCreate): Promise<Channel | null> => {
    try {
      const res = await fetch("/api/channels", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(input),
      });
      if (!res.ok) {
        const body = await res.json();
        throw new Error(body.error?.message || "Failed to create channel");
      }
      const json = await res.json();
      await fetchData();
      return json.data as Channel;
    } catch (e) {
      setError(e instanceof Error ? e.message : "Unknown error");
      return null;
    }
  }, [fetchData]);

  const update = useCallback(async (id: string, input: ChannelUpdate): Promise<Channel | null> => {
    try {
      const res = await fetch(`/api/channels/${id}`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(input),
      });
      if (!res.ok) {
        const body = await res.json();
        throw new Error(body.error?.message || "Failed to update channel");
      }
      const json = await res.json();
      await fetchData();
      return json.data as Channel;
    } catch (e) {
      setError(e instanceof Error ? e.message : "Unknown error");
      return null;
    }
  }, [fetchData]);

  const remove = useCallback(async (id: string): Promise<boolean> => {
    try {
      const res = await fetch(`/api/channels/${id}`, { method: "DELETE" });
      if (!res.ok) {
        const body = await res.json();
        throw new Error(body.error?.message || "Failed to delete channel");
      }
      await fetchData();
      return true;
    } catch (e) {
      setError(e instanceof Error ? e.message : "Unknown error");
      return false;
    }
  }, [fetchData]);

  return { data, pagination, isLoading, error, refetch: fetchData, create, update, remove };
}

/** Fetch a single Channel by ID */
export function useChannel(id: string | null) {
  const [data, setData] = useState<Channel | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchData = useCallback(async () => {
    if (!id) return;
    setIsLoading(true);
    setError(null);
    try {
      const res = await fetch(`/api/channels/${id}`);
      if (!res.ok) {
        const body = await res.json();
        throw new Error(body.error?.message || "Channel not found");
      }
      const json = await res.json();
      setData(json.data as Channel);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Unknown error");
    } finally {
      setIsLoading(false);
    }
  }, [id]);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  return { data, isLoading, error, refetch: fetchData };
}
