/**
 * useSettings Hook
 *
 * React hook for accessing typed app settings in client components.
 *
 * @generated by settings-registry module
 */

"use client";

import { createContext, useContext, useState, useCallback } from "react";
import type { AppSettings, GlobalSettings, ModuleSettings } from "@/lib/settings";
import { defaultSettings, mergeSettings } from "@/lib/settings";

interface SettingsContextValue {
  settings: AppSettings;
  updateGlobal: (patch: Partial<GlobalSettings>) => void;
  updateModule: <K extends keyof ModuleSettings>(
    moduleKey: K,
    patch: Partial<ModuleSettings[K]>
  ) => void;
}

const SettingsContext = createContext<SettingsContextValue>({
  settings: defaultSettings,
  updateGlobal: () => {},
  updateModule: () => {},
});

export function SettingsProvider({
  children,
  initialOverrides,
}: {
  children: React.ReactNode;
  initialOverrides?: Partial<AppSettings>;
}) {
  const [settings, setSettings] = useState<AppSettings>(
    initialOverrides ? mergeSettings(initialOverrides) : defaultSettings
  );

  const updateGlobal = useCallback((patch: Partial<GlobalSettings>) => {
    setSettings((prev) => ({
      ...prev,
      global: { ...prev.global, ...patch },
    }));
  }, []);

  const updateModule = useCallback(
    <K extends keyof ModuleSettings>(
      moduleKey: K,
      patch: Partial<ModuleSettings[K]>
    ) => {
      setSettings((prev) => ({
        ...prev,
        modules: {
          ...prev.modules,
          [moduleKey]: { ...prev.modules[moduleKey], ...patch },
        },
      }));
    },
    []
  );

  return (
    <SettingsContext.Provider value={{ settings, updateGlobal, updateModule }}>
      {children}
    </SettingsContext.Provider>
  );
}

/**
 * Access the full settings object.
 */
export function useSettings(): AppSettings {
  return useContext(SettingsContext).settings;
}

/**
 * Access global settings only.
 */
export function useGlobalSettings(): GlobalSettings {
  return useContext(SettingsContext).settings.global;
}

/**
 * Access a specific module's settings.
 */
export function useModuleSettings<K extends keyof ModuleSettings>(
  moduleKey: K
): ModuleSettings[K] {
  return useContext(SettingsContext).settings.modules[moduleKey];
}

/**
 * Access settings update functions.
 */
export function useSettingsUpdater() {
  const { updateGlobal, updateModule } = useContext(SettingsContext);
  return { updateGlobal, updateModule };
}
