/**
 * Hook: useFilters — URL-synced filter state
 * Auto-generated by filter-engine module
 */

"use client";

import { useCallback, useMemo } from "react";
import { useRouter, useSearchParams, usePathname } from "next/navigation";

interface UseFiltersOptions {
  /** Filter keys to track in URL params */
  keys: string[];
}

interface UseFiltersReturn {
  values: Record<string, string>;
  setFilter: (key: string, value: string) => void;
  setFilters: (updates: Record<string, string>) => void;
  clearFilters: () => void;
  hasActiveFilters: boolean;
}

export function useFilters({ keys }: UseFiltersOptions): UseFiltersReturn {
  const router = useRouter();
  const pathname = usePathname();
  const searchParams = useSearchParams();

  const values = useMemo(() => {
    const result: Record<string, string> = {};
    for (const key of keys) {
      result[key] = searchParams.get(key) || "";
    }
    return result;
  }, [searchParams, keys]);

  const updateUrl = useCallback(
    (newParams: Record<string, string>) => {
      const params = new URLSearchParams(searchParams.toString());
      for (const [key, value] of Object.entries(newParams)) {
        if (value) {
          params.set(key, value);
        } else {
          params.delete(key);
        }
      }
      // Reset to page 1 on filter change
      params.delete("page");
      router.push(`${pathname}?${params.toString()}`);
    },
    [router, pathname, searchParams]
  );

  const setFilter = useCallback(
    (key: string, value: string) => {
      updateUrl({ [key]: value });
    },
    [updateUrl]
  );

  const setFilters = useCallback(
    (updates: Record<string, string>) => {
      updateUrl(updates);
    },
    [updateUrl]
  );

  const clearFilters = useCallback(() => {
    const cleared: Record<string, string> = {};
    for (const key of keys) {
      cleared[key] = "";
    }
    updateUrl(cleared);
  }, [keys, updateUrl]);

  const hasActiveFilters = useMemo(
    () => Object.values(values).some((v) => v !== ""),
    [values]
  );

  return { values, setFilter, setFilters, clearFilters, hasActiveFilters };
}
