/**
 * API Route: Review — List & Create
 * Auto-generated by crud-scaffolder module
 */

import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { reviewCreateSchema } from "@/lib/schemas/review";

export async function GET(request: NextRequest) {
  try {
    const supabase = await createClient();
    const { data: { user }, error: authError } = await supabase.auth.getUser();
    if (authError || !user) {
      return NextResponse.json(
        { error: { code: "UNAUTHORIZED", message: "Not authenticated" } },
        { status: 401 }
      );
    }

    const url = new URL(request.url);
    const page = parseInt(url.searchParams.get("page") || "1", 10);
    const limit = Math.min(parseInt(url.searchParams.get("limit") || "20", 10), 100);
    const ALLOWED_SORT_FIELDS = new Set(["rating", "feedback", "created_at", "updated_at"]);
    const rawSort = url.searchParams.get("sort") || "created_at";
    const sortBy = ALLOWED_SORT_FIELDS.has(rawSort) ? rawSort : "created_at";
    const ascending = url.searchParams.get("order") === "asc";
    const offset = (page - 1) * limit;

    let query = supabase
      .from("reviews")
      .select("*", { count: "exact" })
      .eq("user_id", user.id)
      .order(sortBy, { ascending })
      .range(offset, offset + limit - 1);

    // Search filter
    const search = url.searchParams.get("search");
    if (search) {
      query = query.or(`feedback.ilike.%${search}%`);
    }

    const { data, error, count } = await query;
    if (error) {
      return NextResponse.json(
        { error: { code: "DB_ERROR", message: error.message } },
        { status: 500 }
      );
    }

    return NextResponse.json({
      data,
      pagination: {
        page,
        limit,
        total: count ?? 0,
        totalPages: Math.ceil((count ?? 0) / limit),
      },
    });
  } catch (_err) {
    return NextResponse.json(
      { error: { code: "INTERNAL", message: "Internal server error" } },
      { status: 500 }
    );
  }
}

export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient();
    const { data: { user }, error: authError } = await supabase.auth.getUser();
    if (authError || !user) {
      return NextResponse.json(
        { error: { code: "UNAUTHORIZED", message: "Not authenticated" } },
        { status: 401 }
      );
    }

    const body = await request.json();
    const parsed = reviewCreateSchema.safeParse(body);
    if (!parsed.success) {
      return NextResponse.json(
        { error: { code: "VALIDATION", message: "Invalid input", details: parsed.error.flatten() } },
        { status: 400 }
      );
    }

    const { data, error } = await supabase
      .from("reviews")
      .insert({ ...parsed.data, user_id: user.id })
      .select()
      .single();

    if (error) {
      return NextResponse.json(
        { error: { code: "DB_ERROR", message: error.message } },
        { status: 500 }
      );
    }

    return NextResponse.json({ data }, { status: 201 });
  } catch (_err) {
    return NextResponse.json(
      { error: { code: "INTERNAL", message: "Internal server error" } },
      { status: 500 }
    );
  }
}
