/**
 * Zod validation schemas for Channel
 * Auto-generated by schema-registry module
 *
 * Single source of truth — TypeScript types are derived from these schemas.
 */

import { z } from "zod";

/** Full Channel schema (as stored in DB, including system fields) */
export const channelSchema = z.object({
  id: z.string().uuid(),
  user_id: z.string().uuid(),
  name: z.string().min(1),
  type: z.string().min(1),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});

/** Schema for creating a new Channel (no id/timestamps/user_id) */
export const channelCreateSchema = z.object({
  name: z.string().min(1),
  type: z.string().min(1),
});

/** Schema for updating an existing Channel (all fields optional) */
export const channelUpdateSchema = z.object({
  name: z.string().min(1).optional(),
  type: z.string().min(1).optional(),
});

/** Full Channel row type (as returned from DB) */
export type Channel = z.infer<typeof channelSchema>;

/** Input type for creating a new Channel */
export type ChannelCreate = z.infer<typeof channelCreateSchema>;

/** Input type for updating an existing Channel */
export type ChannelUpdate = z.infer<typeof channelUpdateSchema>;
