/**
 * Zod validation schemas for Comment
 * Auto-generated by schema-registry module
 *
 * Single source of truth — TypeScript types are derived from these schemas.
 */

import { z } from "zod";

/** Full Comment schema (as stored in DB, including system fields) */
export const commentSchema = z.object({
  id: z.string().uuid(),
  user_id: z.string().uuid(),
  body: z.string().min(1),
  target_type: z.string().min(1),
  target_id: z.string().uuid(),
  parent_id: z.string().uuid().optional(),
  author_id: z.string().uuid(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});

/** Schema for creating a new Comment (no id/timestamps/user_id) */
export const commentCreateSchema = z.object({
  body: z.string().min(1),
  target_type: z.string().min(1),
  target_id: z.string().uuid(),
  parent_id: z.string().uuid().optional(),
  author_id: z.string().uuid(),
});

/** Schema for updating an existing Comment (all fields optional) */
export const commentUpdateSchema = z.object({
  body: z.string().min(1).optional(),
  target_type: z.string().min(1).optional(),
  target_id: z.string().uuid().optional(),
  parent_id: z.string().uuid().optional(),
  author_id: z.string().uuid().optional(),
});

/** Full Comment row type (as returned from DB) */
export type Comment = z.infer<typeof commentSchema>;

/** Input type for creating a new Comment */
export type CommentCreate = z.infer<typeof commentCreateSchema>;

/** Input type for updating an existing Comment */
export type CommentUpdate = z.infer<typeof commentUpdateSchema>;
