/**
 * Zod validation schemas for Invoice
 * Auto-generated by schema-registry module
 *
 * Single source of truth — TypeScript types are derived from these schemas.
 */

import { z } from "zod";

/** Full Invoice schema (as stored in DB, including system fields) */
export const invoiceSchema = z.object({
  id: z.string().uuid(),
  user_id: z.string().uuid(),
  amount: z.number(),
  currency: z.string().min(1).default("usd"),
  status: z.enum(["paid", "pending", "failed", "refunded"]),
  stripe_invoice_id: z.string().min(1),
  pdf_url: z.string().url().optional(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});

/** Schema for creating a new Invoice (no id/timestamps/user_id) */
export const invoiceCreateSchema = z.object({
  amount: z.number(),
  currency: z.string().min(1).default("usd"),
  status: z.enum(["paid", "pending", "failed", "refunded"]),
  stripe_invoice_id: z.string().min(1),
  pdf_url: z.string().url().optional(),
});

/** Schema for updating an existing Invoice (all fields optional) */
export const invoiceUpdateSchema = z.object({
  amount: z.number().optional(),
  currency: z.string().min(1).default("usd").optional(),
  status: z.enum(["paid", "pending", "failed", "refunded"]).optional(),
  stripe_invoice_id: z.string().min(1).optional(),
  pdf_url: z.string().url().optional(),
});

/** Full Invoice row type (as returned from DB) */
export type Invoice = z.infer<typeof invoiceSchema>;

/** Input type for creating a new Invoice */
export type InvoiceCreate = z.infer<typeof invoiceCreateSchema>;

/** Input type for updating an existing Invoice */
export type InvoiceUpdate = z.infer<typeof invoiceUpdateSchema>;
