/**
 * Zod validation schemas for Listing
 * Auto-generated by schema-registry module
 *
 * Single source of truth — TypeScript types are derived from these schemas.
 */

import { z } from "zod";

/** Full Listing schema (as stored in DB, including system fields) */
export const listingSchema = z.object({
  id: z.string().uuid(),
  user_id: z.string().uuid(),
  title: z.string().min(1),
  description: z.string().min(1),
  price: z.number(),
  status: z.enum(["available", "sold"]),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});

/** Schema for creating a new Listing (no id/timestamps/user_id) */
export const listingCreateSchema = z.object({
  title: z.string().min(1),
  description: z.string().min(1),
  price: z.number(),
  status: z.enum(["available", "sold"]),
});

/** Schema for updating an existing Listing (all fields optional) */
export const listingUpdateSchema = z.object({
  title: z.string().min(1).optional(),
  description: z.string().min(1).optional(),
  price: z.number().optional(),
  status: z.enum(["available", "sold"]).optional(),
});

/** Full Listing row type (as returned from DB) */
export type Listing = z.infer<typeof listingSchema>;

/** Input type for creating a new Listing */
export type ListingCreate = z.infer<typeof listingCreateSchema>;

/** Input type for updating an existing Listing */
export type ListingUpdate = z.infer<typeof listingUpdateSchema>;
