/**
 * Zod validation schemas for Message
 * Auto-generated by schema-registry module
 *
 * Single source of truth — TypeScript types are derived from these schemas.
 */

import { z } from "zod";

/** Full Message schema (as stored in DB, including system fields) */
export const messageSchema = z.object({
  id: z.string().uuid(),
  user_id: z.string().uuid(),
  content: z.string().min(1),
  conversation_id: z.string().uuid(),
  sender_id: z.string().uuid(),
  message_type: z.enum(["text", "image", "file", "system"]),
  read_at: z.string().datetime(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});

/** Schema for creating a new Message (no id/timestamps/user_id) */
export const messageCreateSchema = z.object({
  content: z.string().min(1),
  conversation_id: z.string().uuid(),
  sender_id: z.string().uuid(),
  message_type: z.enum(["text", "image", "file", "system"]),
  read_at: z.string().datetime(),
});

/** Schema for updating an existing Message (all fields optional) */
export const messageUpdateSchema = z.object({
  content: z.string().min(1).optional(),
  conversation_id: z.string().uuid().optional(),
  sender_id: z.string().uuid().optional(),
  message_type: z.enum(["text", "image", "file", "system"]).optional(),
  read_at: z.string().datetime().optional(),
});

/** Full Message row type (as returned from DB) */
export type Message = z.infer<typeof messageSchema>;

/** Input type for creating a new Message */
export type MessageCreate = z.infer<typeof messageCreateSchema>;

/** Input type for updating an existing Message */
export type MessageUpdate = z.infer<typeof messageUpdateSchema>;
