/**
 * Zod validation schemas for Order
 * Auto-generated by schema-registry module
 *
 * Single source of truth — TypeScript types are derived from these schemas.
 */

import { z } from "zod";

/** Full Order schema (as stored in DB, including system fields) */
export const orderSchema = z.object({
  id: z.string().uuid(),
  user_id: z.string().uuid(),
  listing_id: z.string().uuid(),
  buyer_id: z.string().uuid(),
  seller_id: z.string().uuid(),
  amount: z.number(),
  status: z.enum(["pending", "paid", "shipped", "completed", "cancelled", "refunded"]).default("pending"),
  payment_intent_id: z.string().min(1),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});

/** Schema for creating a new Order (no id/timestamps/user_id) */
export const orderCreateSchema = z.object({
  listing_id: z.string().uuid(),
  buyer_id: z.string().uuid(),
  seller_id: z.string().uuid(),
  amount: z.number(),
  status: z.enum(["pending", "paid", "shipped", "completed", "cancelled", "refunded"]).default("pending"),
  payment_intent_id: z.string().min(1),
});

/** Schema for updating an existing Order (all fields optional) */
export const orderUpdateSchema = z.object({
  listing_id: z.string().uuid().optional(),
  buyer_id: z.string().uuid().optional(),
  seller_id: z.string().uuid().optional(),
  amount: z.number().optional(),
  status: z.enum(["pending", "paid", "shipped", "completed", "cancelled", "refunded"]).default("pending").optional(),
  payment_intent_id: z.string().min(1).optional(),
});

/** Full Order row type (as returned from DB) */
export type Order = z.infer<typeof orderSchema>;

/** Input type for creating a new Order */
export type OrderCreate = z.infer<typeof orderCreateSchema>;

/** Input type for updating an existing Order */
export type OrderUpdate = z.infer<typeof orderUpdateSchema>;
