/**
 * Zod validation schemas for Payment
 * Auto-generated by schema-registry module
 *
 * Single source of truth — TypeScript types are derived from these schemas.
 */

import { z } from "zod";

/** Full Payment schema (as stored in DB, including system fields) */
export const paymentSchema = z.object({
  id: z.string().uuid(),
  user_id: z.string().uuid(),
  stripe_payment_id: z.string().min(1),
  amount: z.number(),
  currency: z.string().min(1),
  status: z.enum(["pending", "completed", "failed", "refunded"]),
  payment_method: z.string().min(1),
  description: z.string().min(1),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});

/** Schema for creating a new Payment (no id/timestamps/user_id) */
export const paymentCreateSchema = z.object({
  stripe_payment_id: z.string().min(1),
  amount: z.number(),
  currency: z.string().min(1),
  status: z.enum(["pending", "completed", "failed", "refunded"]),
  payment_method: z.string().min(1),
  description: z.string().min(1),
});

/** Schema for updating an existing Payment (all fields optional) */
export const paymentUpdateSchema = z.object({
  stripe_payment_id: z.string().min(1).optional(),
  amount: z.number().optional(),
  currency: z.string().min(1).optional(),
  status: z.enum(["pending", "completed", "failed", "refunded"]).optional(),
  payment_method: z.string().min(1).optional(),
  description: z.string().min(1).optional(),
});

/** Full Payment row type (as returned from DB) */
export type Payment = z.infer<typeof paymentSchema>;

/** Input type for creating a new Payment */
export type PaymentCreate = z.infer<typeof paymentCreateSchema>;

/** Input type for updating an existing Payment */
export type PaymentUpdate = z.infer<typeof paymentUpdateSchema>;
