/**
 * Zod validation schemas for Profile
 * Auto-generated by schema-registry module
 *
 * Single source of truth — TypeScript types are derived from these schemas.
 */

import { z } from "zod";

/** Full Profile schema (as stored in DB, including system fields) */
export const profileSchema = z.object({
  id: z.string().uuid(),
  user_id: z.string().uuid(),
  display_name: z.string().min(1).optional(),
  avatar_url: z.string().url().optional(),
  bio: z.string().min(1).optional(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});

/** Schema for creating a new Profile (no id/timestamps/user_id) */
export const profileCreateSchema = z.object({
  display_name: z.string().min(1).optional(),
  avatar_url: z.string().url().optional(),
  bio: z.string().min(1).optional(),
});

/** Schema for updating an existing Profile (all fields optional) */
export const profileUpdateSchema = z.object({
  display_name: z.string().min(1).optional(),
  avatar_url: z.string().url().optional(),
  bio: z.string().min(1).optional(),
});

/** Full Profile row type (as returned from DB) */
export type Profile = z.infer<typeof profileSchema>;

/** Input type for creating a new Profile */
export type ProfileCreate = z.infer<typeof profileCreateSchema>;

/** Input type for updating an existing Profile */
export type ProfileUpdate = z.infer<typeof profileUpdateSchema>;
