/**
 * Zod validation schemas for Reaction
 * Auto-generated by schema-registry module
 *
 * Single source of truth — TypeScript types are derived from these schemas.
 */

import { z } from "zod";

/** Full Reaction schema (as stored in DB, including system fields) */
export const reactionSchema = z.object({
  id: z.string().uuid(),
  user_id: z.string().uuid(),
  emoji: z.string().min(1),
  target_type: z.string().min(1),
  target_id: z.string().uuid(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});

/** Schema for creating a new Reaction (no id/timestamps/user_id) */
export const reactionCreateSchema = z.object({
  emoji: z.string().min(1),
  target_type: z.string().min(1),
  target_id: z.string().uuid(),
});

/** Schema for updating an existing Reaction (all fields optional) */
export const reactionUpdateSchema = z.object({
  emoji: z.string().min(1).optional(),
  target_type: z.string().min(1).optional(),
  target_id: z.string().uuid().optional(),
});

/** Full Reaction row type (as returned from DB) */
export type Reaction = z.infer<typeof reactionSchema>;

/** Input type for creating a new Reaction */
export type ReactionCreate = z.infer<typeof reactionCreateSchema>;

/** Input type for updating an existing Reaction */
export type ReactionUpdate = z.infer<typeof reactionUpdateSchema>;
