/**
 * Zod validation schemas for Review
 * Auto-generated by schema-registry module
 *
 * Single source of truth — TypeScript types are derived from these schemas.
 */

import { z } from "zod";

/** Full Review schema (as stored in DB, including system fields) */
export const reviewSchema = z.object({
  id: z.string().uuid(),
  user_id: z.string().uuid(),
  rating: z.number(),
  feedback: z.string().min(1),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});

/** Schema for creating a new Review (no id/timestamps/user_id) */
export const reviewCreateSchema = z.object({
  rating: z.number(),
  feedback: z.string().min(1),
});

/** Schema for updating an existing Review (all fields optional) */
export const reviewUpdateSchema = z.object({
  rating: z.number().optional(),
  feedback: z.string().min(1).optional(),
});

/** Full Review row type (as returned from DB) */
export type Review = z.infer<typeof reviewSchema>;

/** Input type for creating a new Review */
export type ReviewCreate = z.infer<typeof reviewCreateSchema>;

/** Input type for updating an existing Review */
export type ReviewUpdate = z.infer<typeof reviewUpdateSchema>;
