/**
 * Zod validation schemas for Shop
 * Auto-generated by schema-registry module
 *
 * Single source of truth — TypeScript types are derived from these schemas.
 */

import { z } from "zod";

/** Full Shop schema (as stored in DB, including system fields) */
export const shopSchema = z.object({
  id: z.string().uuid(),
  user_id: z.string().uuid(),
  name: z.string().min(1),
  description: z.string().min(1),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});

/** Schema for creating a new Shop (no id/timestamps/user_id) */
export const shopCreateSchema = z.object({
  name: z.string().min(1),
  description: z.string().min(1),
});

/** Schema for updating an existing Shop (all fields optional) */
export const shopUpdateSchema = z.object({
  name: z.string().min(1).optional(),
  description: z.string().min(1).optional(),
});

/** Full Shop row type (as returned from DB) */
export type Shop = z.infer<typeof shopSchema>;

/** Input type for creating a new Shop */
export type ShopCreate = z.infer<typeof shopCreateSchema>;

/** Input type for updating an existing Shop */
export type ShopUpdate = z.infer<typeof shopUpdateSchema>;
