/**
 * Zod validation schemas for Upload
 * Auto-generated by schema-registry module
 *
 * Single source of truth — TypeScript types are derived from these schemas.
 */

import { z } from "zod";

/** Full Upload schema (as stored in DB, including system fields) */
export const uploadSchema = z.object({
  id: z.string().uuid(),
  user_id: z.string().uuid(),
  file_name: z.string().min(1),
  file_url: z.string().url(),
  file_type: z.string().min(1),
  file_size: z.number(),
  storage_path: z.string().min(1),
  alt_text: z.string().min(1),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});

/** Schema for creating a new Upload (no id/timestamps/user_id) */
export const uploadCreateSchema = z.object({
  file_name: z.string().min(1),
  file_url: z.string().url(),
  file_type: z.string().min(1),
  file_size: z.number(),
  storage_path: z.string().min(1),
  alt_text: z.string().min(1),
});

/** Schema for updating an existing Upload (all fields optional) */
export const uploadUpdateSchema = z.object({
  file_name: z.string().min(1).optional(),
  file_url: z.string().url().optional(),
  file_type: z.string().min(1).optional(),
  file_size: z.number().optional(),
  storage_path: z.string().min(1).optional(),
  alt_text: z.string().min(1).optional(),
});

/** Full Upload row type (as returned from DB) */
export type Upload = z.infer<typeof uploadSchema>;

/** Input type for creating a new Upload */
export type UploadCreate = z.infer<typeof uploadCreateSchema>;

/** Input type for updating an existing Upload */
export type UploadUpdate = z.infer<typeof uploadUpdateSchema>;
