/**
 * Zod validation schemas for User
 * Auto-generated by schema-registry module
 *
 * Single source of truth — TypeScript types are derived from these schemas.
 */

import { z } from "zod";

/** Full User schema (as stored in DB, including system fields) */
export const userSchema = z.object({
  id: z.string().uuid(),
  user_id: z.string().uuid(),
  username: z.string().min(1),
  email: z.string().email(),
  password: z.string().min(1),
  role: z.enum(["buyer", "seller"]),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});

/** Schema for creating a new User (no id/timestamps/user_id) */
export const userCreateSchema = z.object({
  username: z.string().min(1),
  email: z.string().email(),
  password: z.string().min(1),
  role: z.enum(["buyer", "seller"]),
});

/** Schema for updating an existing User (all fields optional) */
export const userUpdateSchema = z.object({
  username: z.string().min(1).optional(),
  email: z.string().email().optional(),
  password: z.string().min(1).optional(),
  role: z.enum(["buyer", "seller"]).optional(),
});

/** Full User row type (as returned from DB) */
export type User = z.infer<typeof userSchema>;

/** Input type for creating a new User */
export type UserCreate = z.infer<typeof userCreateSchema>;

/** Input type for updating an existing User */
export type UserUpdate = z.infer<typeof userUpdateSchema>;
